models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./uvahelpr_models:/app
    ports:
      - "8001:8000"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata db.json && mod_wsgi-express start-server --reload-on-changes ./uvahelpr_models/wsgi.py ./uvahelpr_web/wsgi.py --url-alias /static ./static"
#
exp:
    image: tp33/django
    links:
      -  models:models-api
      -  kafka:kafka
      -  es:es
    volumes:
      - ./uvahelpr_exp:/app
    ports:
      - "8002:8000"
    command: bash -c "mod_wsgi-express start-server --reload-on-changes ./uvahelpr_exp/wsgi.py"

web:
    image: tp33/django
    links:
      -  exp:exp-api
    volumes:
      - ./uvahelpr_web:/app
    ports:
      - "8000:8000"
    command: bash -c "mod_wsgi-express start-server --reload-on-changes ./uvahelpr_web/wsgi.py --url-alias /static ./static"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   volumes:
      - ./:/app
   command: bash -c "python indexES.py"

spark-master:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
  container_name: spark-master
  hostname: spark-master
  environment:
    MASTER: spark://spark-master:7077
    SPARK_CONF_DIR: /conf
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./data:/tmp/data

spark-worker:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  container_name: spark-worker
  hostname: spark-worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 512m
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - spark-master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ./data:/tmp/data