models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./uvahelpr_models:/app
    ports:
      - "8001:8000"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata db.json && mod_wsgi-express start-server --reload-on-changes ./uvahelpr_models/wsgi.py ./uvahelpr_web/wsgi.py --url-alias /static ./static"
#
exp:
    image: tp33/django
    links:
      -  models:models-api
      -  kafka:kafka
      -  es:es
    volumes:
      - ./uvahelpr_exp:/app
    ports:
      - "8002:8000"
    command: bash -c "mod_wsgi-express start-server --reload-on-changes ./uvahelpr_exp/wsgi.py"

web1:
    image: tp33/django
    links:
      -  exp:exp-api
    volumes:
      - ./uvahelpr_web:/app
    ports:
      - "8003:8000"
    command: bash -c "mod_wsgi-express start-server --reload-on-changes ./uvahelpr_web/wsgi.py --url-alias /static ./static"

web2:
    image: tp33/django
    links:
      -  exp:exp-api
    volumes:
      - ./uvahelpr_web:/app
    ports:
      - "8004:8000"
    command: bash -c "mod_wsgi-express start-server --reload-on-changes ./uvahelpr_web/wsgi.py --url-alias /static ./static"

lb:
    build: ./haproxy-build
    links:
      -  web1:web1
      -  web2:web2
    ports:
      - "8000:8000"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   volumes:
      - ./:/app
   command: bash -c "python indexES.py"