models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./uvahelpr_models:/app
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata db.json && mod_wsgi-express start-server --reload-on-changes ./uvahelpr_models/wsgi.py ./uvahelpr_web/wsgi.py --url-alias /static ./static"

exp:
    image: tp33/django
    links:
      -  models:models-api
      -  kafka:kafka
      -  es:es
    volumes:
      - ./uvahelpr_exp:/app
    command: bash -c "mod_wsgi-express start-server --reload-on-changes ./uvahelpr_exp/wsgi.py"

web:
    image: tp33/django
    links:
      -  exp:exp-api
    volumes:
      - ./uvahelpr_web:/app
    environment:
      - SECRET_KEY='c!$ghzr8orm3s(2a*0ei!)0u0ezgiu**9#nwm)bjz8-f&+madh'
    ports:
      - "8000:8000"
    command: bash -c "mod_wsgi-express start-server --reload-on-changes ./uvahelpr_web/wsgi.py --url-alias /static ./static"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   volumes:
      - ./:/app
   command: bash -c "python indexES.py"
